apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name  }}-php
spec:
  selector:
    app: {{ .Release.Name  }}-php
  ports:
  - name: http
    port: {{ .Values.image.port }}
    targetPort: {{ .Values.image.targetPort }}
  type: LoadBalancer